### ISSUE TITLE
Null exception on swap_icon_refresh

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/dex#284]
### Describe the problem you discovered

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _SwapTokenIconRefreshState.build.<anonymous closure> (package:/ui/views/aeswap_swap/layouts/components/swap_icon_refresh.dart:53:29)
#1      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#9      RendererBinding.dispatchEvent (pack<…>
```

warning, user can refresh when no token is filled

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/dex/pull/281/commits/e33a55a63a17f0f27703cc640d2a570d62f09a2e
